/* 
https://www.iconfinder.com/icons/1243689/call_phone_icon
Creative Commons (Attribution 3.0 Unported);
https://www.iconfinder.com/Makoto_msk */

export const storeProducts = [
  {
    id: 1,
    title: "Samsung Galaxy A32 Dual SIM",
    img: "img/product-1.png",
    price: 4650,
    company: "Samsung",
    info: "Brand: Samsung, Model name: A32, Dimensions: 158.9 x 73.6 x 8.4 mm, Weight: 184g, Build: Glass front, plastic back, plastic frame, Sim: Dual SIM (Nano-SIM, dual stand-by), Type: Super AMOLED, 90Hz, 800 nits, Size: 6.4 inches, Resolution: 1080 x 2400 pixels, OS: Android 11",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 2,
    title: "Samsung Galaxy Note 20 Mobile",
    img: "img/product-2.png",
    price: 13300,
    company: "Samsung",
    info: "The Powerphone: The large smartphone with 6.7 Infinity-O display gives you plenty of room for efficient working and action-packed gaming. And a powerful 4,300 mAh battery with fast charge function means you don’t have to run out of power as fast. Let your ideas run wild: With the S Pen you can write on your Andoid smartphone almost like a real pen. The S Pen can do much more: The Bluetooth function and S Pen gestures make it a productive tool for your Galaxy Note20. Seamless PC collaboration: Just on your smartphone, now on your PC.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 3,
    title: "Huawei Nova 7i Dual SIM",
    img: "img/product-3.png",
    price: 3599,
    company: "Huawei",
    info: "CPU: Octa-core, RAM: 8 GB, Storage: 128 GB, Four rear cameras: Quad (48 MP + 8 MP + 2 MP + 2MP) Selfie Camera: 16 MP, Display: 6.4 inches, weight: 183g (including the battery), 4200 mAh (Typical Value)Android",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 4,
    title: "POCO X3 Pro Dual SIM ",
    img: "img/product-4.png",
    price: 4299,
    company: "Xiaomi",
    info: "Brand: Xiaomi, Model number: Poco X3 Pro,  Dimensions: 165.3 x 76.8 x 9.4 mm, Weight: 215 g, Capacity: 5160 mAh, Type: Non-removable Li-polymer battery, Charging: 33W Fast charging, Processor: Qualcomm Snapdragon, RAM: 6 Gigabytes, ROM: 128 Gigabytes",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 5,
    title: " Redmi 9T Dual SIM ",
    img: "img/product-5.png",
    price: 3099,
    company: "Xiaomi",
    info: "Operating System: Android 10, MIUI 12, RAM: 6GB, ROM: 128GB, Camera Effective Pixels: 48MP, 8MP, 2MP, 2MP, Selfie camera: 8MP, Display: 6.53 Inches, IPS LCD capacitive touchscreen, 16M colors, 395 nits HDR, Chipset: Qualcomm SM6115 Snapdragon 662 (11 nm), Battery: Li-Po 6000mAh fast battery charging 18W",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 6,
    title: "OPPO A93 Dual SIM",
    img: "img/product-6.png",
    price: 4700,
    company: "OPPO",
    info: "Fast Charge : Yes, Mobile Phone Type : Dual SIM, RAM:128GB, Brand : OPPO, Operating System Type : Android    Chipset manufacturer : MediaTek, Battery Capacity in mAh : 4000, Display Size (Inch) : 6.43, Cellular Network Technology : 4G LTE",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 7,
    title: "HUAWEI Y8p Dual SIM",
    img: "img/product-7.png",
    price: 3444,
    company: "HUAWEI",
    info: "CPU: Octa-core,RAM: 6 GB, Storage: 128 GB, Four rear cameras: Triple: 48 MP, 8 MP, 4 MP, Selfie Camera: 16 MP, Display: 6.3 inches, 163 g (including the battery), Non-removable Li-Po 4000 mAh battery, Android 10",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 8,
    title: "OPPO A15 Dual SIM",
    img: "img/product-8.png",
    price: 2200,
    company: "OPPO",
    info: "Brand : OPPO, Color : Blue, Operating System Type : Android, Storage Capacity : 32 GB, RAM:2GB, Number Of SIM : Dual SIM, Rear Camera Resolution : 13 megapixels, Mobile Phone Type : Dual SIM, Cellular Network Technology : 4G LTE, Chipset manufacturer : MediaTek, Display Size (Inch) : 6.5 inches",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 9,
    title: "OPPO Reno 5 Dual SIM",
    img: "img/product-9.png",
    price: 5700,
    company: "OPPO",
    info: "Fast Charge : Yes, Mobile Phone Type : Dual SIM, RAM:8GB,Memory Storage: 128GB, Operating System Type : Android, Chipset manufacturer : Qualcomm Snapdragon, Battery Capacity in mAh : 4000 - 5000 milliampere_hour, Display Size (Inch) : 6.4 inches, Cellular Network Technology : 4G LTE, Model Number : oppo reno 5 black",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 10,
    title: "Smashed Iphone",
    img: "img/product-8.png",
    price: 2000,
    company: "Apple",
    info: "Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics, DIY coloring book mixtape craft beer sartorial hella blue bottle. Tote bag wolf authentic try-hard put a bird on it mumblecore. Unicorn lumbersexual master cleanse blog hella VHS, vaporware sartorial church-key cardigan single-origin coffee lo-fi organic asymmetrical. Taxidermy semiotics celiac stumptown scenester normcore, ethical helvetica photo booth gentrify.",
    inCart: false,
    count: 0,
    total: 0,
  },
];

export const detailProduct = {
  id: 1,
  title: "Google Pixel - Black",
  img: "img/product-1.png",
  price: 1000,
  company: "Google",
  info: "Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics, DIY coloring book mixtape craft beer sartorial hella blue bottle. Tote bag wolf authentic try-hard put a bird on it mumblecore. Unicorn lumbersexual master cleanse blog hella VHS, vaporware sartorial church-key cardigan single-origin coffee lo-fi organic asymmetrical. Taxidermy semiotics celiac stumptown scenester normcore, ethical helvetica photo booth gentrify.",
  inCart: false,
  count: 0,
  total: 0,
};
